ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS name_ar VARCHAR;
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS name_ar VARCHAR;
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS desc_ar TEXT;
